language: java
jdk:
- oraclejdk8
addons:
  ssh_known_hosts:
  - student.bmstu.cloud
before_deploy:
  - ./before_install.sh
deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: master
